### PR TITLE
Build DLL using cross-compilation

### PR DESCRIPTION
**Pull request by bertfrees**

### CODE REVIEW

**Comment by phajdan** [comment]
Thanks for the PR! I'm not sure if I quite understand the purpose of it though. Could you please give some more context?

**Comment by bertfrees** [comment]
Sorry I should have given some more explanation. We are using libhyphen in a Java application that is supposed to be cross-platform, and did not find a pre-compiled DLL at the time. Maybe I didn't look very hard though, because I always like to be able to build my libraries from source, preferably with cross-compilation because I don't have a Windows build tool chain. Besides, it looked like the project didn't have any other build instructions for a DLL yet, nor any Windows-specific build files.

In order to be able to do `./configure --host i586-mingw32` && `make`, I had to add the GCC option `-no-undefined`. I wasn't really sure what it's for. After some more investigation it turns out that it is a libtool thing: see http://web.mit.edu/gnu/doc/html/libtool.html#SEC40.

**Comment by phajdan** [comment]
Thanks for the context! Changes to Makefile.am and README look totally fine to me. If you posted a PR with just that, I could quickly merge it.

What I'm still trying to understand are changes to tests/Makefile.am. Using example.exe and wine seems to specific to your use case.

**Comment by bertfrees** [comment]
Oh that... it's because I wanted to run the test suite on my DLL and this seemed like the cleanest way to do it. It would have been more code if I would have done it in tests/test.sh.

I basically just generate a wrapper script named `example` that uses wine to invoke `example.exe`. The "dos2unix" is because example.exe produces Windows line endings. (Another solution would have been to make the diff command in [test.sh#L56](https://github.com/snaekobbi/hyphen/blob/51132a3819b6cd3bd11d38129691c47f5b5238dc/tests/test.sh#L56) ignore differences in line endings.)

**Comment by bertfrees** [comment]
But maybe you're right about wine. I guess people could be building this on Cygwin in which case they don't need wine. Feel free to drop that part. But maybe running make check should be prevented somehow if you ran configure with `--host i586-mingw32`.

**Comment by bertfrees** [comment]
By the way, how do LibreOffice, Firefox etc. build Hyphen for Windows? Do you know?

**Comment by phajdan** [comment]
No, I haven't checked. Do you want to update this PR? Should we close it?

**Comment by bertfrees** [comment]
I don't really know how to solve the tests/Makefile.am thing. If you have an idea, please tell me how I should fix it and I'll do it. Otherwise, I'd say just drop my changes to tests/Makefile.am.

**Comment by phajdan** [comment]
The Makefile.am change might be too specific to include into hyphen. Feel free to open another PR for remaining changes.

**Pull request closed without merging**
